baseurl = "https://blog.ebemunk.com/"
languageCode = "en-us"
title = "Thinking Through the Party"
theme = "lexo"
paginate = 20

pygmentscodefences = true

googleAnalytics = "UA-212741-11"
disqusShortname = "ebemunk"

disableKinds = ["taxonomy", "section"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
  author = "ebemunk"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:slug/"

[markup.goldmark.renderer]
  unsafe = true
